<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="content-wrapper">
    <h1>
        <span><?php echo $block->escapeHtml(__('Your request was successfully')) ?></span>
    </h1>

    <?php if ($block->getCustomerName()) :?>
        <h3>
            <?php echo $block->getCustomerName() ?>
        </h3>
    <?php else : ?>
        <h3><?php echo $block->escapeHtml(__('Anonymous')) ?></h3>
    <?php endif;?>

    <a href="<?php echo $block->generateUrl() ?>"><?php echo $block->escapeHtml(__('Link to JSON controller')) ?></a>
</div>
