<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="content-wrapper">
    <h1>
        <span>Your request was successfully</span>
    </h1>

    <?php if ($block->getName()):?>
        <h3>
            <?= /* @escapeNotVerified */ $block->getName(); ?>
        </h3>
    <?php endif;?>

    <?php if ($block->getLastName()):?>
        <h3>
            <?= /* @escapeNotVerified */ $block->getLastName(); ?>
        </h3>
    <?php endif;?>

    <a href="<?= $block->generateUrl() ?>">Link to JSON controller</a>
</div>
