<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="content-wrapper">
    <h1>
        <span>Your request was successfully</span>
    </h1>

    <?php if ($block->getCustomerName()):?>
        <h3>
            <?= $block->getCustomerName(); ?>
        </h3>
    <?php else: ?>
        <h3>Anonymous</h3>
    <?php endif;?>

    <a href="<?= $block->generateUrl() ?>">Link to JSON controller</a>
</div>
