<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>

<div class="catalog-product-view-tab-request-sample-form">
    <h2><?= $block->escapeHtml(__('Make my style'))?></h2>
    <div class="actions dropdown example-dropdown-5">
        <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
            <span>span + dropdown</span>
        </span>
        <ul class="dropdown">
            <li>
                <span class="item">One</span>
            </li>
            <li>
                <span class="item">Two</span>
            </li>
            <li>
                <span class="item">Three</span>
            </li>
        </ul>
    </div>
</div>
