<?php use Magento\Cms\Block\Block;

/* @var $block \ElTrubetskaia\CustomWidget\Block\Widget\BannerHomepage */

?>

<?php if($block->getBlockId()): ?>
    <main>
        <div class="media">
            <div class="media-body">
                <?= $block->getLayout()->createBlock(Block::class)->setBlockId($block->getBlockId())->toHtml();?>
                <?php if($block->getWidgetTitle()): ?>
                    <a id="widget-banner-homepage" class="action primary" href="<?= $block->getUrl('geekhub-cms') ?>"><?php echo $block->getWidgetTitle(); ?></a>
                <?php endif; ?>
            </div>
        </div>
    </main>
<?php endif; ?>
