<?php

use Magento\Customer\Helper\Address;
use Magento\Customer\Block\Widget\Fax;
use Magento\Customer\Block\Widget\Telephone;
use Magento\Customer\Block\Widget\Company;
use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Block\Widget\Taxvat;
use Magento\Customer\Block\Widget\Dob;
use Magento\Customer\Block\Widget\Name;

/**
  * @var \Magento\Customer\Block\Form\Register $block
 */
?>
<h3>
    <a href="javascript:void(0)"
       id="registration-for-dealer"
       data-mage-init='{"modalRegistrationForm": {}}'
    >
        <?php echo $block->escapeHtml(__('Registration for dealer')) ?>
    </a>
</h3>

<div id="registration-for-dealer-modal" style="display:none;">
    <div id="registration-for-dealer-modal-content">
        <form class="form create account form-create-account"
              action="<?php echo $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post" id="modal-form-validate"
              enctype="multipart/form-data"
              autocomplete="off">
            <?php echo /* @noEscape */ $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset create info">
                <legend class="legend">
                    <span><?php echo $block->escapeHtml(__('Personal Information')) ?></span>
                </legend>
                <br>
                <input type="hidden"
                       name="success_url"
                       value="<?php echo $block->escapeUrl($block->getSuccessUrl()) ?>">
                <input type="hidden"
                       name="error_url"
                       value="<?php echo $block->escapeUrl($block->getErrorUrl()) ?>">
                <div class="field field-name-firstname required">
                    <label class="label" for="firstname"><span><?php echo $block->escapeHtml(__('First Name')) ?></span></label>
                    <div class="control">
                        <input type="text"
                               id="modal-firstname"
                               name="modal-firstname"
                               value="<?php echo $block->escapeHtml($block->getFirstName()) ?>"
                               title="<?php echo $block->escapeHtmlAttr(__('First Name')) ?>"
                               class="input-text required-entry"
                               data-validate="{required:true}"
                               autocomplete="off"
                               aria-required="true">
                    </div>
                </div>
                <div class="field field-name-lastname required">
                    <label class="label" for="lastname">
                        <span><?php echo $block->escapeHtml(__('Last Name')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               id="modal-lastname"
                               name="modal-lastname"
                               value="<?php echo $block->escapeHtml($block->getLastName()) ?>"
                               title="<?php echo $block->escapeHtmlAttr(__('Last Name')) ?>"
                               class="input-text required-entry"
                               data-validate="{required:true}"
                               autocomplete="off"
                               aria-required="true">
                    </div>
                </div>
                <?php if ($block->isNewsletterEnabled()) : ?>
                    <div class="field choice newsletter">
                        <input type="checkbox"
                               name="modal_is_subscribed"
                               title="<?php echo $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
                               value="1"
                               id="modal_is_subscribed"
                                <?php if ($block->getFormData()->getIsSubscribed()) : ?>
                                    checked="checked"
                                <?php endif; ?>
                               class="checkbox">
                        <label for="modal_is_subscribed" class="label">
                            <span><?php echo $block->escapeHtml(__('Sign Up for Newsletter')) ?></span>
                        </label>
                    </div>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $block->getChildHtml('customer.form.register.newsletter') ?>
                <?php endif ?>

                <?php $_dob = $block->getLayout()->createBlock(Dob::class) ?>
                <?php if ($_dob->isEnabled()) : ?>
                    <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                <?php endif ?>

                <?php $_taxvat = $block->getLayout()->createBlock(Taxvat::class) ?>
                <?php if ($_taxvat->isEnabled()) : ?>
                    <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                <?php endif ?>

                <?php $_gender = $block->getLayout()->createBlock(Gender::class) ?>
                <?php if ($_gender->isEnabled()) : ?>
                    <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                <?php endif ?>
            </fieldset>
            <?php if ($block->getShowAddressFields()) : ?>
                <fieldset class="fieldset address">
                    <legend class="legend">
                        <span><?php echo $block->escapeHtml(__('Address Information')) ?></span>
                    </legend><br>
                    <input type="hidden" name="create_address" value="1" />

                    <?php $company = $block->getLayout()->createBlock(Company::class) ?>
                    <?php if ($company->isEnabled()) : ?>
                        <?php echo $company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                    <?php endif ?>

                    <?php $telephone = $block->getLayout()->createBlock(Telephone::class) ?>
                    <?php if ($telephone->isEnabled()) : ?>
                        <?php echo $telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
                    <?php endif ?>

                    <?php $fax = $block->getLayout()->createBlock(Fax::class) ?>
                    <?php if ($fax->isEnabled()) : ?>
                        <?php echo $fax->setFax($block->getFormData()->getFax())->toHtml() ?>
                    <?php endif ?>

                    <?php $streetValidationClass = $this->helper(Address::class)
                        ->getAttributeValidationClass('street'); ?>

                    <div class="field street required">
                        <label for="street_1" class="label">
                            <span><?php echo /* @noEscape */ $block->getAttributeData()
                                    ->getFrontendLabel('street') ?></span>
                        </label>
                        <div class="control">
                            <input type="text"
                                   name="street[]"
                                   value="<?php echo $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>"
                                   title="<?php echo /* @noEscape */ $block->getAttributeData()
                                       ->getFrontendLabel('street') ?>"
                                   id="street_1"
                                   class="input-text <?php echo $block->escapeHtmlAttr($_streetValidationClass) ?>">
                            <div class="nested">
                                <?php $streetValidationClass = trim(str_replace('required-entry', '', $streetValidationClass)); ?>
                                <?php for ($_i = 2, $_n = $this->helper(
                                    Address::class
                                )->getStreetLines(); $_i <= $_n; $_i++) : ?>
                                    <div class="field additional">
                                        <label class="label" for="street_<?php echo /* @noEscape */ $_i ?>">
                                            <span><?php echo $block->escapeHtml(__('Address')) ?></span>
                                        </label>
                                        <div class="control">
                                            <input type="text"
                                                   name="street[]"
                                                   value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>"
                                                   title="<?php echo $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>"
                                                   id="street_<?php echo /* @noEscape */ $_i ?>"
                                                   class="input-text <?php echo $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                        </div>
                                    </div>
                                <?php endfor; ?>
                            </div>
                        </div>
                    </div>

                    <div class="field required">
                        <label for="city" class="label">
                            <span>
                                <?php echo /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>
                            </span>
                        </label>
                        <div class="control">
                            <input type="text"
                                   name="city"
                                   value="<?php echo $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>"
                                   title="<?php echo /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                                   class="input-text <?= $block->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('city')) ?>"
                                   id="city">
                        </div>
                    </div>

                    <div class="field region required">
                        <label for="region_id" class="label">
                            <span>
                                <?php echo /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>
                            </span>
                        </label>
                        <div class="control">
                            <select id="region_id"
                                    name="region_id"
                                    title="<?php echo /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                                    class="validate-select"
                                    style="display:none;">
                                <option value="">
                                    <?php echo $block->escapeHtml(__('Please select a region, state or province.')) ?>
                                </option>
                            </select>
                            <input type="text"
                                   id="region"
                                   name="region"
                                   value="<?php echo $block->escapeHtml($block->getRegion()) ?>"
                                   title="<?php echo /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                                   class="input-text <?php echo $block->escapeHtmlAttr(
                                           $this->helper(Address::class)
                                               ->getAttributeValidationClass('region')
                                   ) ?>"
                                   style="display:none;">
                        </div>
                    </div>

                    <div class="field zip required">
                        <label for="zip" class="label">
                            <span>
                                <?php echo /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>
                            </span>
                        </label>
                        <div class="control">
                            <input type="text"
                                   name="postcode"
                                   value="<?php echo $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>"
                                   title="<?php echo /* @noEscape */ $block->getAttributeData()
                                       ->getFrontendLabel('postcode') ?>"
                                   id="zip"
                                   class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(
                                       Address::class
                                   )->getAttributeValidationClass('postcode')) ?>">
                        </div>
                    </div>

                    <div class="field country required">
                        <label for="country" class="label">
                            <span>
                                <?php echo /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?>
                            </span>
                        </label>
                        <div class="control">
                            <?php echo $block->getCountryHtmlSelect(null, 'country_id', 'modal-country', 'Country') ?>
                        </div>
                    </div>
                    <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                    <?php if ($addressAttributes) : ?>
                        <?php $addressAttributes->setEntityType('customer_address'); ?>
                        <?php $addressAttributes->setFieldIdFormat('address:%1$s')
                            ->setFieldNameFormat('address[%1$s]');?>
                        <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                        <?php echo $addressAttributes->setShowContainer(false)->toHtml() ?>
                    <?php endif;?>
                    <input type="hidden" name="default_billing" value="1">
                    <input type="hidden" name="default_shipping" value="1">
                </fieldset>

            <?php endif; ?>
            <fieldset class="fieldset create account"
                      data-hasrequired="<?php echo $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <legend class="legend">
                    <span><?php echo $block->escapeHtml(__('Sign-in Information')) ?></span>
                </legend>
                <br>
                <div class="field required">
                    <label for="modal_email_address" class="label">
                        <span><?php echo $block->escapeHtml(__('Email')) ?></span>
                    </label>
                    <div class="control">
                        <input type="email"
                               name="email"
                               autocomplete="email"
                               id="modal_email_address"
                               value="<?php echo $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>"
                               title="<?php echo $block->escapeHtmlAttr(__('Email')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               class="input-text"
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field modal-password required">
                    <label for="password" class="label">
                        <span><?php echo $block->escapeHtml(__('Password')) ?></span>
                    </label>
                    <div class="control">
                        <input type="password" name="modal-password" id="modal-password"
                               title="<?php echo $block->escapeHtmlAttr(__('Password')) ?>"
                               class="input-text"
                               data-password-min-length="<?php echo $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                               data-password-min-character-sets="<?php echo $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                               data-validate="{required:true, 'validate-customer-password':true}"
                               autocomplete="off">
                        <div id="password-strength-meter-container"
                             data-role="password-strength-meter"
                             aria-live="polite">
                            <div id="modal-password-strength-meter" class="password-strength-meter">
                                <?php echo $block->escapeHtml(__('Password Strength')) ?>:
                                <span id="modal-password-strength-meter-label" data-role="modal-password-strength-meter-label">
                            <?php echo $block->escapeHtml(__('No Password')) ?>
                        </span>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="field confirmation required">
                    <label for="password-confirmation" class="label">
                        <span><?php echo $block->escapeHtml(__('Confirm Password')) ?></span>
                    </label>
                    <div class="control">
                        <input type="password"
                               name="modal-password_confirmation"
                               title="<?php echo $block->escapeHtmlAttr(__('Confirm Password')) ?>"
                               id="modal-password-confirmation"
                               class="input-text"
                               data-validate="{required:true, equalTo:'#modal-password'}"
                               autocomplete="off">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info') ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit"
                            class="action submit primary"
                            title="<?php echo $block->escapeHtmlAttr(__('Create an Account')) ?>">
                        <span><?php echo $block->escapeHtml(__('Create an Account')) ?></span>
                    </button>
                </div>
                <div class="secondary">
                    <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
                        <span><?php echo $block->escapeHtml(__('Back')) ?></span>
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>

<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "#registration-for-dealer": {-->
<!--            "modalRegistrationForm": {-->
<!--                "config": ""-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--</script>-->

<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){

        var dataForm = $('#modal-form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
            <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        }).find('input:text').attr('autocomplete', 'off');

    });
</script>
<?php if ($block->getShowAddressFields()): ?>
    <script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.modal-password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>

